name: Mod compatibility request
description: Request support for a specific mod or mod version
labels: ["Compatibility", "Enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this compatibility request!
  - type: input
    id: mod-name
    attributes:
      label: Mod name
      description: The name of the mod that you want support for.
    validations:
      required: true
  - type: input
    id: mod-version
    attributes:
      label: Mod version
      description: The version of the mod that you want support for.
      placeholder: "1.0.0"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Why should compatibility be added for this mod / version?
      description: A clear and concise description of why this mod / version should be supported.
    validations:
      required: true
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Any additional information that you would like to share.
