name: Mod incompatibility report
description: Report a mod incompatibility
labels: ["Bug", "Compatibility"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this incompatibility report!
  - type: input
    id: this-mod-version
    attributes:
      label: Mod version
      description: The version that you are using of this mod.
      placeholder: "1.0.0"
    validations:
      required: true
  - type: input
    id: mod-name
    attributes:
      label: Other mod name
      description: The name of the mod that you have issues with.
    validations:
      required: true
  - type: input
    id: mod-version
    attributes:
      label: Other mod version
      description: The version of the mod that you have issues with.
      placeholder: "1.0.0"
    validations:
      required: true
  - type: textarea
    id: mod-list
    attributes:
      label: Mod list
      description: |
        Please provide a full list of mods that you were using to while the bug happened.

        If you are using Thunderstore Mod Manager or r2modmanager you can get a full list like this:
        1. Go into the Settings of your profile.
        2. Click on the 'Modpacks' tab.
        3. Click on 'Show dependency strings'.
        4. Copy the content of the dialog and paste it here.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe what happend
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
      description: Give a description of how to reproduce the bug. Please walk through them step by step.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: media
    attributes:
      label: Media
      description: If applicable, add screenshots, logs or a video to help explain your problem.
    validations:
      required: false
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Any additional information that you would like to share.
